package com.xray.domain.model;

public enum Category {
    LIQUIDITY, OPERATING_CASH_FLOW, ACTIVITY_GROWTH, DEBT_SERVICE, LEVERAGE,
    PAYMENT_BEHAVIOUR, DELINQUENCY, CONCENTRATION, TAX_REGULARITY, MOMENTUM
}
