package com.xray.domain.model;

/** The 22 level indicators of SPEC §6. MOM_PERSISTENCE is a derived feature, not listed here. */
public enum IndicatorId {
    LIQ_RUNWAY, LIQ_BUFFER, LIQ_MIN_BALANCE,
    CF_NOCF_MARGIN, CF_VOLATILITY, CF_IN_OUT_RATIO,
    ACT_COLLECTIONS_GROWTH,
    DEBT_DSCR, DEBT_LINE_UTIL,
    LEV_DEBT_TO_CF, LEV_FACTORING_RELIANCE, LEV_FUNDING_COST,
    PAY_DSO, PAY_DPO, PAY_SUPPLIER_LATENESS, PAY_OVERDUE_PAYABLES,
    DEL_OVERDUE_RECEIVABLES, DEL_AGING_90,
    CON_HHI_CUSTOMERS, CON_HHI_SUPPLIERS, CON_CUSTOMER_CHURN,
    TAX_REGULARITY
}
